[versions]
junit-jupiter-engine = "5.10.3"
jqwik-engine = "1.9.0"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
# for property-based tests
jqwik-engine = { module = "net.jqwik:jqwik", version.ref = "jqwik-engine" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.22" }
